//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaaProizv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolgnosti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dolgnosti()
        {
            this.Sotrudniki = new HashSet<Sotrudniki>();
        }
    
        public int IdDolgnost { get; set; }
        public string Nazvanie { get; set; }
        public decimal Oklad { get; set; }
        public string Opysanie { get; set; }
        public Nullable<int> OtdelId { get; set; }
    
        public virtual Otdeli Otdeli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrudniki> Sotrudniki { get; set; }
    }
}
