//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaaProizv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otpuska
    {
        public int IdOtpuska { get; set; }
        public int IdSotr { get; set; }
        public Nullable<System.DateTime> DataNachalaOtpuska { get; set; }
        public Nullable<System.DateTime> DataOkonchaniyaOtpuska { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Sotrudniki Sotrudniki1 { get; set; }
    }
}
