//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaaProizv
{
    using System;
    using System.Collections.Generic;
    
    public partial class PovishemieKvalific
    {
        public int IdPov { get; set; }
        public System.DateTime DatePov { get; set; }
        public string Kvalifkaciya { get; set; }
        public string Kurs { get; set; }
        public int IdSotr { get; set; }
        public string Sertificat { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Sotrudniki Sotrudniki1 { get; set; }
    }
}
