//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaaProizv
{
    using System;
    using System.Collections.Generic;
    
    public partial class RavocheeVremya
    {
        public int IdRabocheeVremya { get; set; }
        public Nullable<int> IdSotr { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> VremyaHachalaRab { get; set; }
        public Nullable<System.TimeSpan> VremyaOkonchaniyaRab { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Status Status { get; set; }
    }
}
