//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaaProizv
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchtatnoeRaspisanie
    {
        public int IdRasp { get; set; }
        public int IdDolgnost { get; set; }
        public int Oklad { get; set; }
        public int KolvoStavok { get; set; }
    
        public virtual Dolgnosti Dolgnosti { get; set; }
    }
}
