//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractikaaProizv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudniki()
        {
            this.Otpuska = new HashSet<Otpuska>();
            this.RavocheeVremya = new HashSet<RavocheeVremya>();
        }
    
        public int IdSotr { get; set; }
        public string Familia { get; set; }
        public string Imya { get; set; }
        public Nullable<int> IdDolgnost { get; set; }
        public Nullable<System.DateTime> DataPriem { get; set; }
    
        public virtual Dolgnosti Dolgnosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otpuska> Otpuska { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RavocheeVremya> RavocheeVremya { get; set; }
    }
}
